<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<script>
  //网络请求：aaa -> 自己处理（10行）
  //处理：aaa222 -> 自己处理（10行）
  //处理：aaa222333 ->自己处理
  new Promise(resolve => {
    setTimeout(()=>{
      resolve('aaa')
    },1000)
  }).then(res =>{
    //1.自己处理10行代码
    console.log(res,'第一层的10行处理结果');

    //2.对结果进行第一次处理
    return new Promise(resolve => {
      resolve(res + '222')
    })
  }).then(res =>{
    console.log(res,'第二层的10行的处理结果');

    return new Promise(resolve => {
      resolve(res + '333')
    })
  }).then(res =>{
    console.log(res,'第三层10行的处理结果');
    console.log('----------------------');
  })


  //上述代码的简写
  new Promise(resolve => {
    setTimeout(()=>{
      resolve('aaa')
    },1000)
  }).then(res =>{
    //1.自己处理10行代码
    console.log(res,'第一层的10行处理结果');

    //2.对结果进行第一次处理
    return Promise.resolve(res + '222')
  }).then(res =>{
    console.log(res,'第二层的10行的处理结果');

    return Promise.resolve(res + '333')
  }).then(res =>{
    console.log(res,'第三层10行的处理结果');
    console.log('----------------------');
  })


  //上述代码的再次简写
  new Promise(resolve => {
    setTimeout(()=>{
      resolve('aaa')
    },1000)
  }).then(res =>{
    //1.自己处理10行代码
    console.log(res,'第一层的10行处理结果');

    //2.对结果进行第一次处理
    return res + '222'
  }).then(res =>{
    console.log(res,'第二层的10行的处理结果');

    return res + '333'
  }).then(res =>{
    console.log(res,'第三层10行的处理结果');
    console.log('----------------------');
  })

  //reject 的使用
  new Promise(resolve => {
    setTimeout(()=>{
      resolve('aaa')
    },1000)
  }).then(res =>{
    //1.自己处理10行代码
    console.log(res,'第一层的10行处理结果');

    //2.对结果进行第一次处理
    return Promise.reject('error message');//程序到这就会直接卡断跳到最后处理catch
  }).then(res =>{
    console.log(res,'第二层的10行的处理结果');

    return res + '333'
  }).then(res =>{
    console.log(res,'第三层10行的处理结果');
  }).catch(err =>{
    console.log(err);
  })
</script>
</body>
</html>
